name: Build wheels

on:
  # on new tag
  push:
    tags:
      - "*"

  # manually trigger
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 是 Intel 架構 (x86_64)，如果未來需要 Apple Silicon (M1/M2) 需增加 macos-14
        os: [windows-2022, macos-13]

    steps:
      - uses: actions/checkout@v4

      - name: Set MacOS compiler
        if: runner.os == 'macOS'
        run: |
          brew install gcc@13;
          echo "CXX=gcc-13" >> $GITHUB_ENV
          echo "CC=gcc-13" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          # 預設會 build 所有的 CPython 版本 (包括 3.12, 3.13)
          # 略過 PyPy 和 Windows 32-bit
          CIBW_SKIP: pp* *win32*
          
          # macOS 上強制使用 GCC (因 setup.py 依賴 -fopenmp)
          CXX: ${{ env.CXX }}
          CC: ${{ env.CC }}
        with:
          package-dir: ./python
          output-dir: ./python/wheelhouse

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./python/wheelhouse